name: Python Application Test

on:
  push:
    branches: [ "dev","main" ]
  pull_request:
    branches: [ "dev","main" ]

jobs:

  build:
    defaults:
      run:
        working-directory: backend/
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9, "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Lint with Black
        uses: psf/black@stable
        with:
          options: "--exclude=tests/"
          src: "backend/src/"
      - name: Lint with Isort
        run: |
            pip install isort
            isort . --profile black
      # - name: Lint with Ruff
      #   uses: stefanzweifel/git-auto-commit-action@v6
      #   with:
      #     commit_message: 'style fixes by ruff'
      # - run: |
      #       pip install ruff
      #       ruff check .
      #       ruff fix .
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          # Version of PostgreSQL to use
          postgresql version: 12.1-alpine
          # POSTGRES_DB - name for the default database that is created
          postgresql db: hello_fastapi_dev
          # POSTGRES_USER - create the specified user with superuser power
          postgresql user: hello_fastapi
          # POSTGRES_PASSWORD - superuser password
          postgresql password: hello_fastapi
      # - name: Test with pytest
      #   run: |
      #     pip install pytest pytest-asyncio pytest-xdist
      #     pytest --cov --cov-report xml . 
  lint:
        runs-on: ubuntu-latest 
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: 3.9
        - run: pip install ruff
        - run: | 
            ruff check . --exclude "tests/ 
            ruff --fix . --exclude "tests/
        - uses: stefanzweifel/git-auto-commit-action@v6
          with:
            commit_message: 'style fixes by ruff'
